[Config]
MinimumVersion=24

[Distribution]
Distribution=rosa
Release=rosa13
Architecture=arm64

[Output]
Format=disk
CompressOutput=
# nand u-boot does not support
# 4k sectors
SectorSize=512

[Content]
Packages=
    coreutils
    dnf
    dracut
    iproute2
    kernel-6.1-rockchip
    locales-en
    neovim
    openssh-server
    rosa-repos
    systemd
    uboot-tools
    vi
    minicom
#    mbpoll
    rosa-repos-contrib

Bootable=no
Autologin=yes
RootPassword=hashed:$6$Gild0mhh.pqO8/Kx$JgD3Mo3YM1UTqMxi0jK4MgBuwU.cIthQs4IHXwtaCozs1qlnNNkB1ikZ2mpaUELaAOdnUa8xl00KDd9QFS5/R/
RootShell=/usr/bin/bash
Locale=en_US.UTF-8
Timezone=Europe/Moscow
Hostname=napi-c
WithDocs=no
CleanPackageMetadata=false
[Host]
PackageDirectories=/work/local-repo
